Repository team-focus-time/focus-time, pull requests merged in 2025-09, with the labels that each got.

#16 [feature] 회원가입, 로그인 페이지 기능 구현
  login/Login.css
  login/Login.html
  login/Login.js
  register/Register.css
  register/Register.html
  register/Register.js
Labels: feature

#25 🔀 feat: 투두리스트 리스트, 등록 화면, 로컬스토리지 저장 기능 구현
  todolist/TodoList.css
  todolist/TodoList.html
  todolist/TodoList.js
Labels: feature, style

#30 feat: 메인페이지 버튼 클릭 시 로그인 페이지 전환
  index.html
  main.js
  style.css
Labels: feature

#36 cont: 메인페이지 버튼 기능 수정
  index.html
  main.js
Labels: refactor

#39 CSS 일부 수정, 네비게이션 바에 링크 추가
  todolist/TodoList.css
  todolist/TodoList.html
Labels: style

#41 style: 메인 페이지 반응형
  index.html
  style.css
Labels: style

#42 CSS 일부 수정
  todolist/TodoList.css
  todolist/TodoList.html
Labels: style

#45 style: 메인페이지 반응형
  style.css
Labels: style

#49 style: 로그인 페이지 반응형
  login/Login.css
Labels: style

#51 feat: 로그인페이지 알럿 버튼 기능 수정
  login/Login.js
Labels: hot

#53 feat: 스탑워치 페이지 로그아웃 버튼 기능 수정
  stopwatch/StopWatch.css
  stopwatch/StopWatch.html
  stopwatch/StopWatch.js
Labels: feature

#56 🔀 2차 배포
  .github/workflows/PULL_REQUEST_TEMPLATE.md
  README.md
  assets/images/hsg.png
  assets/images/htu.png
  assets/images/jey.png
  assets/images/ywj.png
  index.html
  login/Login.css
  login/Login.js
  main.js
  stopwatch/StopWatch.css
  stopwatch/StopWatch.html
  stopwatch/StopWatch.js
  style.css
  timer/Timer.css
  timer/Timer.html
  timer/Timer.js
  todolist/TodoList.css
  todolist/TodoList.html
  todolist/TodoList.js
Labels: merge

#59 style: 회원가입 페이지 반응형
  register/Register.css
Labels: style

#61 style: 로그인 페이지 수정
  login/Login.css
Labels: style

#64 style: 푸터 반응형
  stopwatch/StopWatch.css
  timer/Timer.css
Labels: style

#71 style: 투두리스트 스타일
  todolist/TodoList.css
  todolist/TodoList.html
  todolist/TodoList.js
Labels: style

#74 🔀 docs: README.md 내용 추가
  README.md
Labels: documentation

#75 style: 히스토리 스타일
  history/app.js
  history/index.html
  history/style.css
Labels: style
